[program:euphoria-queue]
command=/usr/bin/php /var/www/euphoria/spark queue:work
directory=/var/www/euphoria
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/euphoria-queue.log