[program:euphoria-web]
command=/usr/bin/php spark serve --host 127.0.0.1 --port 8080
directory=/var/www/euphoria
autostart=true
autorestart=true
user=www-data
stopsignal=TERM
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/euphoria-web.log