<?php
$grouped=[];foreach($media as $item)$grouped[$item['section']][]=$item;
$hero=$grouped['hero'][0]??null;$featured=$grouped['featured'][0]??null;$lineup=array_slice($grouped['lineup']??[],0,6);$gallery=array_slice($grouped['gallery']??[],0,8);
?>
<main class="festival-home">
  <section class="festival-hero" data-testid="home-hero" style="background-image:url('<?= esc($hero['public_url']??'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1900&q=85') ?>')"><div class="festival-hero-scrim"></div><div class="festival-hero-grid"></div><div class="festival-hero-content"><span class="eyebrow cyan">SAGE UNIVERSITY INDORE · EUPHORIA 2026</span><h1>EXPERIENCE THE<br><span>ENERGY.</span> LIVE THE<br><em>EUPHORIA.</em></h1><p><?= esc($hero['caption']??'Three days of performance, competition, technology and campus culture on one electric stage.') ?></p><div class="hero-actions"><a class="button button-neon" href="<?= base_url('registration') ?>" data-testid="hero-register-button">Get your pass ↗</a><a class="button button-ghost" href="#schedule" data-testid="hero-schedule-button">Explore schedule</a><?php if($featured): ?><button class="hero-play" type="button" data-media-open data-media='<?= esc(json_encode($featured), 'attr') ?>' data-testid="hero-video-button"><span>▶</span> Watch teaser</button><?php endif ?></div></div><div class="festival-hero-meta"><div><span>PROGRAMME</span><strong>EUPHORIA 2026</strong></div><div><span>VENUE</span><strong>SAGE University Indore</strong></div><div><span>LIVE EVENTS</span><strong><?= count($events) ?></strong></div></div></section>
  <div class="festival-ribbon"><div>SAGE <i>EUPHORIA</i> SAGE <i>EUPHORIA</i> SAGE <i>EUPHORIA</i></div></div>
  <section id="highlights" class="festival-section"><div class="festival-heading"><div><span class="eyebrow cyan">01 / EUPHORIA HIGHLIGHTS</span><h2>EVERY TALENT<br><em>HAS A STAGE.</em></h2></div><p>From artistic expression to technical innovation and competitive sport—find your frequency.</p></div><div class="highlight-grid" data-testid="highlight-grid"><?php foreach(array_slice($categories,0,6) as $index=>$category): $categoryEvents=array_values(array_filter($events,fn($event)=>(int)$event['category_id']===(int)$category['id'])); ?><a class="highlight-card highlight-<?= $index+1 ?>" href="<?= base_url('category/'.$category['slug']) ?>" data-testid="highlight-<?= esc($category['slug']) ?>"><span>0<?= $index+1 ?></span><div><p><?= count($categoryEvents) ?> LIVE EVENTS</p><h3><?= esc($category['name']) ?></h3><small><?= esc(implode(' · ',array_slice(array_column($categoryEvents,'name'),0,3))) ?></small></div><b>↗</b></a><?php endforeach ?></div></section>
  <?php if($featured): ?><section class="festival-section performer-section" data-testid="featured-performer"><div class="performer-copy"><span class="eyebrow pink">SPECIAL SPOTLIGHT</span><h2><?= esc($featured['title']) ?></h2><p><?= esc($featured['caption']) ?></p><button class="button button-neon" type="button" data-media-open data-media='<?= esc(json_encode($featured),'attr') ?>' data-testid="featured-video-button">Play featured video ▶</button></div><button class="performer-visual" type="button" style="background-image:url('<?= esc($featured['preview_url']) ?>')" data-media-open data-media='<?= esc(json_encode($featured),'attr') ?>' data-testid="featured-media-preview"><span>▶</span><small>WATCH NOW</small></button></section><?php endif ?>
  <section id="lineup" class="festival-section"><div class="festival-heading"><div><span class="eyebrow pink">02 / LINE-UP</span><h2>RHYTHM<br><em>REVELATIONS.</em></h2></div><p>Featured stages, performers and the moments that will define EUPHORIA 2026.</p></div><div class="lineup-grid"><?php foreach($lineup as $index=>$item): ?><button class="lineup-card" type="button" data-media-open data-media='<?= esc(json_encode($item),'attr') ?>' data-testid="lineup-item-<?= $item['id'] ?>"><img src="<?= esc($item['preview_url']) ?>" alt="<?= esc($item['caption']?:$item['title']) ?>"><span>0<?= $index+1 ?></span><div><h3><?= esc($item['title']) ?></h3><p><?= esc($item['caption']) ?></p></div><?php if($item['media_type']==='video'): ?><b>▶</b><?php endif ?></button><?php endforeach ?></div></section>
  <section id="schedule" class="festival-section schedule-section"><div class="festival-heading"><div><span class="eyebrow cyan">03 / DAY-WISE DISPATCH</span><h2>THREE DAYS.<br><em>NO DULL MOMENTS.</em></h2></div><a class="text-link" href="<?= base_url('events') ?>">View complete event details ↗</a></div><div class="schedule-days"><?php $dayNumber=0; foreach(array_slice($schedule,0,3,true) as $date=>$dayEvents): $dayNumber++; ?><article data-testid="schedule-day-<?= $dayNumber ?>"><div class="schedule-date"><span>DAY <?= $dayNumber ?></span><strong><?= date('d M Y',strtotime($date)) ?></strong></div><div class="schedule-event-list"><?php foreach(array_slice($dayEvents,0,8) as $event): ?><a href="<?= base_url('events/'.$event['slug']) ?>"><span><?= date('h:i A',strtotime($event['event_start'])) ?></span><strong><?= esc($event['name']) ?></strong><small><?= esc($event['venue']) ?></small><b>↗</b></a><?php endforeach ?></div></article><?php endforeach ?></div></section>
  <section class="festival-gallery-section"><div class="festival-gallery-heading"><div><span class="eyebrow pink">04 / FESTIVAL IN MOTION</span><h2>THE<br><em>AFTERGLOW.</em></h2></div><a class="button button-neon" href="<?= base_url('gallery') ?>" data-testid="gallery-view-all">View all media ↗</a></div><div class="gallery-strip"><?php foreach($gallery as $item): ?><button type="button" data-media-open data-media='<?= esc(json_encode($item),'attr') ?>' data-testid="gallery-strip-<?= $item['id'] ?>"><img src="<?= esc($item['preview_url']) ?>" alt="<?= esc($item['caption']?:$item['title']) ?>"><?php if($item['media_type']==='video'): ?><span>▶</span><?php endif ?></button><?php endforeach ?></div></section>
  <?= view('partials/media_modal') ?>
</main>