import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiGet, apiPost } from "@/lib/api";
import { queryClient } from "@/lib/queryClient";
import type { AdminPaymentsResponse, PaymentAdminRow, PaymentInitiationResponse, RegistrationResponse } from "@/lib/euphoria";

const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export default function PaymentReconciliation() {
  const [state, setState] = useState("");
  const [selected, setSelected] = useState<PaymentAdminRow | null>(null);
  const payments = useQuery({ queryKey: ["admin-payments", state], queryFn: () => apiGet<AdminPaymentsResponse>(`/admin/payments${state ? `?state=${state}` : ""}`) });
  const verify = useMutation({ mutationFn: ({ id, reason, reference }: { id: string; reason: string; reference: string }) => apiPost<RegistrationResponse>(`/admin/payments/${id}/verify`, { reason, transaction_reference: reference }), onSuccess: () => { setSelected(null); queryClient.invalidateQueries({ queryKey: ["admin-payments"] }); queryClient.invalidateQueries({ queryKey: ["admin-dashboard"] }); queryClient.invalidateQueries({ queryKey: ["admin-registrations"] }); } });
  const retry = useMutation({ mutationFn: (id: string) => apiPost<PaymentInitiationResponse>(`/admin/payments/${id}/retry`), onSuccess: ({ checkout_url }) => window.open(checkout_url, "_blank", "noopener,noreferrer") });
  return <section id="payments" className="ops-panel" data-testid="payment-reconciliation"><div className="ops-panel-heading"><div><p className="eyebrow accent">FINANCE CONTROL</p><h2>Payment reconciliation</h2></div><label className="ops-filter">State<select value={state} onChange={(e) => setState(e.target.value)} data-testid="payment-state-filter"><option value="">All</option><option value="created">Created</option><option value="initiated">Initiated</option><option value="failed">Failed</option><option value="successful">Successful</option><option value="manual_verified">Manual verified</option></select></label></div><div className="responsive-table"><table><thead><tr><th>Registration</th><th>Participant</th><th>Event</th><th>Amount</th><th>Gateway state</th><th>Transaction</th><th>Actions</th></tr></thead><tbody>{payments.data?.data.map((payment) => <tr key={payment.payment_ref} data-testid="payment-row"><td>{payment.registration_id}</td><td>{payment.participant_name}<small>{payment.masked_email}</small></td><td>{payment.event_name}</td><td>{money(payment.amount)}</td><td><span className={`ops-status payment-${payment.state}`}>{payment.state.replaceAll("_", " ")}</span></td><td><code>{payment.txnid || "—"}</code><small>{payment.attempts.length} checkout attempts</small></td><td><div className="ops-row-actions">{!new Set(["successful", "manual_verified"]).has(payment.state) && <><button onClick={() => { if (window.confirm("Open a fresh Easebuzz checkout attempt?")) retry.mutate(payment.registration_id); }} data-testid={`payment-retry-${payment.registration_id}`}>Retry</button><button onClick={() => setSelected(payment)} data-testid={`payment-verify-${payment.registration_id}`}>Verify</button></>}</div></td></tr>)}</tbody></table></div>{selected && <form className="ops-inline-form" data-testid="manual-verification-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); verify.mutate({ id: selected.registration_id, reference: String(data.get("reference")), reason: String(data.get("reason")) }); }}><div><p className="eyebrow">MANUAL VERIFICATION</p><strong>{selected.registration_id} · {money(selected.amount)}</strong></div><label>Transaction reference<input name="reference" required minLength={2} data-testid="manual-reference-input" /></label><label>Reason<input name="reason" required minLength={10} data-testid="manual-reason-input" /></label><button className="button button-yellow" type="submit" disabled={verify.isPending} data-testid="manual-verify-submit">Confirm paid</button><button className="button button-ghost" type="button" onClick={() => setSelected(null)}>Cancel</button>{verify.isError && <p className="form-error">Payment could not be verified. It may already be complete.</p>}</form>}</section>;
}