#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/app/Config/Paths.php';
$paths = new Config\Paths();
require rtrim($paths->systemDirectory, '\\ /') . DIRECTORY_SEPARATOR . 'Boot.php';
exit(CodeIgniter\Boot::bootSpark($paths));