import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link, Navigate } from "react-router-dom";
import BrandLockup from "@/components/BrandLockup";
import { ApiError, apiDelete, apiGet, apiPost, apiPut } from "@/lib/api";
import { queryClient } from "@/lib/queryClient";
import { endSession } from "@/lib/session";
import type { AdminDashboardResponse, AdminEventWrite, AdminRegistrationsResponse, EuphoriaEvent, SessionUser } from "@/lib/euphoria";

const blankEvent = (): AdminEventWrite => ({
  category_id: "cultural", name: "", slug: "", short_description: "", description: "", event_type: "competition", registration_type: "individual", fee: 0, capacity: 250, venue: "SAGE University Indore", status: "draft", min_team_size: null, max_team_size: null, banner_url: "", event_date: "15 September 2026", event_time: "10:00 AM – 6:00 PM", registration_deadline: "14 September 2026 · 11:59 PM", eligibility: "Open to eligible students with a valid institutional ID.", rules: ["Carry your registration confirmation and institutional ID."], prizes: ["Merit certificates and prizes as announced."], coordinator_name: "EUPHORIA Event Desk", coordinator_contact: "SAGE University Indore", schedule: [{ time: "10:00 AM", title: "Event begins" }], event_days: [{ label: "Day 1", date: "2026-09-15" }],
});

const toWrite = (event: EuphoriaEvent): AdminEventWrite => ({
  category_id: event.category_id, name: event.name, slug: event.slug, short_description: event.short_description ?? "", description: event.description, event_type: event.event_type, registration_type: event.registration_type as "individual" | "team", fee: event.fee, capacity: event.capacity, venue: event.venue, status: event.status as AdminEventWrite["status"], min_team_size: event.min_team_size, max_team_size: event.max_team_size, banner_url: event.banner_url, event_date: event.event_date, event_time: event.event_time, registration_deadline: event.registration_deadline, eligibility: event.eligibility, rules: event.rules, prizes: event.prizes, coordinator_name: event.coordinator_name, coordinator_contact: event.coordinator_contact, schedule: event.schedule, event_days: event.event_days.map(({ label, date }) => ({ label, date })),
});

const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export default function AdminPreview() {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<AdminEventWrite | null>(null);
  const auth = useQuery({ queryKey: ["session"], queryFn: () => apiGet<SessionUser>("/auth/me"), retry: false });
  const dashboard = useQuery({ queryKey: ["admin-dashboard"], queryFn: () => apiGet<AdminDashboardResponse>("/admin/dashboard"), enabled: auth.data?.role === "admin" });
  const registrations = useQuery({ queryKey: ["admin-registrations"], queryFn: () => apiGet<AdminRegistrationsResponse>("/admin/registrations"), enabled: auth.data?.role === "admin" });
  const categories = useMemo(() => Array.from(new Map((dashboard.data?.events ?? []).map((event) => [event.category_id, event.category_name])).entries()), [dashboard.data]);
  const save = useMutation({
    mutationFn: (payload: AdminEventWrite) => editingId ? apiPut<EuphoriaEvent>(`/admin/events/${editingId}`, payload) : apiPost<EuphoriaEvent>("/admin/events", payload),
    onSuccess: () => { setForm(null); setEditingId(null); ["admin-dashboard", "events", "registration-catalogue"].forEach((key) => queryClient.invalidateQueries({ queryKey: [key] })); },
  });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete<void>(`/admin/events/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-dashboard"] }) });
  const confirm = useMutation({ mutationFn: (id: string) => apiPost(`/admin/registrations/${id}/confirm`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-registrations"] }); queryClient.invalidateQueries({ queryKey: ["admin-dashboard"] }); } });
  if (auth.isLoading) return <main className="ops-loading" data-testid="admin-loading">Checking secure session…</main>;
  if (auth.error instanceof ApiError && auth.error.status === 401) return <Navigate to="/admin/login" replace />;
  if (auth.data?.role !== "admin") return <Navigate to="/admin/login" replace />;
  const stats = dashboard.data?.stats;
  const set = <K extends keyof AdminEventWrite>(key: K, value: AdminEventWrite[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  return <main className="ops-shell"><aside className="ops-sidebar"><Link to="/"><BrandLockup variant="compact" /></Link><nav><a href="#overview">Overview</a><a href="#events">Event management</a><a href="#registrations">Registrations</a><a href="#scans">Entry tracking</a></nav><button className="text-link ops-logout" onClick={() => endSession("/admin/login")} data-testid="admin-logout-button">Sign out</button></aside><section className="ops-content">
    <header><div><p className="eyebrow accent">EUPHORIA OPERATIONS / DATABASE LIVE</p><h1 data-testid="admin-dashboard-title">Command centre</h1><p className="ops-welcome" data-testid="admin-user-name">Signed in as {auth.data.name}</p></div><button className="button button-yellow" onClick={() => { setEditingId(null); setForm(blankEvent()); }} data-testid="admin-create-event-button">+ Create your event</button></header>
    <div id="overview" className="ops-kpis"><div><span>EVENTS</span><strong data-testid="admin-event-count">{stats?.events ?? 0}</strong></div><div><span>REGISTRATIONS</span><strong data-testid="admin-registration-count">{stats?.registrations ?? 0}</strong></div><div><span>VERIFIED REVENUE</span><strong data-testid="admin-revenue">{money(stats?.revenue ?? 0)}</strong></div><div><span>ENTRIES / DUPLICATES</span><strong data-testid="admin-entry-count">{stats?.entries ?? 0}<small> / {stats?.duplicate_attempts ?? 0}</small></strong></div></div>
    {form && <form className="ops-panel event-editor" data-testid="admin-event-form" onSubmit={(event) => { event.preventDefault(); save.mutate(form); }}><div className="ops-panel-heading"><div><p className="eyebrow accent">{editingId ? "EDIT EVENT & PRICING" : "NEW EVENT"}</p><h2>{editingId ? "Update event" : "Create event"}</h2></div><button type="button" className="text-link" onClick={() => setForm(null)} data-testid="event-form-close">Close ×</button></div><div className="event-editor-grid">
      <label>Event name<input value={form.name} required onChange={(e) => set("name", e.target.value)} data-testid="event-name-input" /></label><label>URL slug<input value={form.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="example-event-name" onChange={(e) => set("slug", e.target.value)} data-testid="event-slug-input" /></label>
      <label>Category<select value={form.category_id} onChange={(e) => set("category_id", e.target.value)} data-testid="event-category-select">{categories.map(([id, name]) => <option key={id} value={id} label={name} />)}</select></label><label>Status<select value={form.status} onChange={(e) => set("status", e.target.value as AdminEventWrite["status"])} data-testid="event-status-select"><option value="draft">Draft · hidden</option><option value="scheduled">Scheduled · visible</option><option value="registration_open">Registration Open · live registration</option><option value="registration_closed">Registration Closed</option><option value="live">Live · event day</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>
      <label>Registration fee (₹)<input type="number" min="0" step="1" value={form.fee} onChange={(e) => set("fee", Number(e.target.value))} data-testid="event-fee-input" /></label><label>Capacity<input type="number" min="0" value={form.capacity} onChange={(e) => set("capacity", Number(e.target.value))} data-testid="event-capacity-input" /></label>
      <label>Registration type<select value={form.registration_type} onChange={(e) => set("registration_type", e.target.value as "individual" | "team")} data-testid="event-registration-type-select"><option value="individual">Individual</option><option value="team">Team</option></select></label><label>Venue<input value={form.venue} required onChange={(e) => set("venue", e.target.value)} data-testid="event-venue-input" /></label>
      {form.registration_type === "team" && <><label>Minimum team size<input type="number" min="1" value={form.min_team_size ?? 1} onChange={(e) => set("min_team_size", Number(e.target.value))} data-testid="event-min-team-input" /></label><label>Maximum team size<input type="number" min="1" value={form.max_team_size ?? 4} onChange={(e) => set("max_team_size", Number(e.target.value))} data-testid="event-max-team-input" /></label></>}
      <label className="editor-wide">Short description<input value={form.short_description} required onChange={(e) => set("short_description", e.target.value)} data-testid="event-short-description-input" /></label><label className="editor-wide">Full description<textarea value={form.description} required onChange={(e) => set("description", e.target.value)} data-testid="event-description-input" /></label>
      <label>Display date<input value={form.event_date} required onChange={(e) => set("event_date", e.target.value)} data-testid="event-display-date-input" /></label><label>Display time<input value={form.event_time} required onChange={(e) => set("event_time", e.target.value)} data-testid="event-time-input" /></label><label className="editor-wide">Registration deadline<input value={form.registration_deadline} required onChange={(e) => set("registration_deadline", e.target.value)} data-testid="event-deadline-input" /></label>
    </div><div className="event-days-editor"><div className="ops-panel-heading"><div><p className="eyebrow">QR ENTRY DAYS</p><p>One successful entry is allowed on each configured day.</p></div><button type="button" className="text-link" onClick={() => set("event_days", [...form.event_days, { label: `Day ${form.event_days.length + 1}`, date: "2026-09-15" }])} data-testid="add-event-day-button">+ Add day</button></div>{form.event_days.map((day, index) => <div className="event-day-row" key={index} data-testid="event-day-row"><input aria-label={`Day ${index + 1} label`} value={day.label} onChange={(e) => set("event_days", form.event_days.map((item, itemIndex) => itemIndex === index ? { ...item, label: e.target.value } : item))} /><input aria-label={`Day ${index + 1} date`} type="date" value={day.date} onChange={(e) => set("event_days", form.event_days.map((item, itemIndex) => itemIndex === index ? { ...item, date: e.target.value } : item))} />{form.event_days.length > 1 && <button type="button" onClick={() => set("event_days", form.event_days.filter((_, itemIndex) => itemIndex !== index))}>Remove</button>}</div>)}</div>
      {save.isError && <p className="form-error" data-testid="event-save-error">Event could not be saved. Check the slug, required fields and team sizes.</p>}<div className="editor-actions"><button className="button button-yellow" type="submit" disabled={save.isPending} data-testid="event-save-button">{save.isPending ? "Saving…" : editingId ? "Save event & pricing" : "Create and publish event"}</button></div></form>}
    <section id="events" className="ops-panel"><div className="ops-panel-heading"><div><p className="eyebrow accent">EVENT MANAGEMENT</p><h2>Your events and pricing</h2></div><span>{dashboard.data?.events.length ?? 0} records</span></div><div className="responsive-table"><table><thead><tr><th>Event</th><th>Category</th><th>Price</th><th>Status</th><th>Days</th><th>Actions</th></tr></thead><tbody>{dashboard.data?.events.map((event) => <tr key={event.id} data-testid="admin-event-row"><td><strong>{event.name}</strong><small>/{event.slug}</small></td><td>{event.category_name}</td><td data-testid={`event-price-${event.id}`}>{money(event.fee)}</td><td><span className={`ops-status status-${event.status}`}>{event.status.replaceAll("_", " ")}</span></td><td>{event.event_days.length}</td><td><div className="ops-row-actions"><button onClick={() => { setEditingId(event.id); setForm(toWrite(event)); window.scrollTo({ top: 0, behavior: "smooth" }); }} data-testid={`event-edit-${event.id}`}>Edit / Price</button><Link to={`/events/${event.slug}`}>View</Link><button className="danger" onClick={() => window.confirm(`Delete or cancel ${event.name}?`) && remove.mutate(event.id)} data-testid={`event-delete-${event.id}`}>Delete</button></div></td></tr>)}</tbody></table></div></section>
    <section id="registrations" className="ops-panel"><div className="ops-panel-heading"><div><p className="eyebrow accent">PARTICIPANTS</p><h2>Registrations & passes</h2></div></div><div className="responsive-table"><table><thead><tr><th>Registration</th><th>Participant</th><th>Event</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{registrations.data?.data.map((registration) => <tr key={registration.registration_id} data-testid="admin-registration-row"><td>{registration.registration_id}</td><td>{registration.participant_name}</td><td>{registration.event_name}</td><td>{money(registration.total_amount)}</td><td>{registration.status.replaceAll("_", " ")}</td><td>{registration.status !== "confirmed" ? <button onClick={() => confirm.mutate(registration.registration_id)} data-testid={`registration-confirm-${registration.registration_id}`}>Confirm / complimentary</button> : <Link to={`/pass/${registration.registration_id}`}>Open pass</Link>}</td></tr>)}</tbody></table></div></section>
    <section id="scans" className="ops-panel"><div className="ops-panel-heading"><div><p className="eyebrow accent">LIVE ENTRY TRACKING</p><h2>Recent scanner decisions</h2></div><Link to="/scanner">Open scanner ↗</Link></div><div className="scan-feed">{dashboard.data?.recent_scans.map((scan, index) => <div key={`${scan.created_at}-${index}`} data-testid="admin-scan-row"><span className={`scan-dot ${scan.status}`}></span><div><strong>{scan.participant_name ?? "Unknown QR"}</strong><small>{scan.registration_id ?? scan.message}</small></div><span>{scan.event_name ?? "—"}</span><span>{scan.gate}</span><b>{scan.status.toUpperCase()}</b></div>)}{!dashboard.data?.recent_scans.length && <p>No scans recorded yet.</p>}</div></section>
  </section></main>;
}