<main class="admin-shell">
  <?= view('partials/admin_sidebar',['active'=>'dashboard']) ?>
  <section class="admin-content"><div class="admin-topbar"><div><span class="eyebrow accent" data-testid="dashboard-date"><?= esc(strtoupper(date('l / d F Y'))) ?></span><h1 data-testid="dashboard-title">Command centre</h1></div><div class="admin-user"><span class="user-dot"></span><span data-testid="admin-user-name"><?= esc(session('user_name')) ?></span></div></div>
    <div class="admin-kpi-grid"><div class="kpi kpi-highlight"><span class="eyebrow">TOTAL REGISTRATIONS</span><strong data-testid="dashboard-total-registrations"><?= esc($stats['registrations']) ?></strong><span class="kpi-label"><?= esc($stats['pending']) ?> pending payment</span></div><div class="kpi"><span class="eyebrow">CONFIRMED</span><strong data-testid="dashboard-confirmed"><?= esc($stats['confirmed']) ?></strong><span class="kpi-label">valid participant records</span></div><div class="kpi"><span class="eyebrow">TODAY'S ENTRIES</span><strong data-testid="dashboard-today-entries"><?= esc($stats['entries']) ?></strong><span class="kpi-label"><?= esc($stats['attendance_percent']) ?>% of <?= esc($stats['expected']) ?> expected</span></div><div class="kpi"><span class="eyebrow">VERIFIED REVENUE</span><strong data-testid="dashboard-revenue"><?= esc(money($stats['revenue'])) ?></strong><span class="kpi-label">successful payments only</span></div></div>
    <div class="ops-strip"><div><span class="eyebrow">ACTIVE CATEGORIES</span><strong><?= esc($stats['categories']) ?></strong></div><div><span class="eyebrow">TOTAL EVENTS</span><strong><?= esc($stats['events']) ?></strong></div><div><span class="eyebrow">DUPLICATE ATTEMPTS</span><strong class="warning-text" data-testid="dashboard-duplicates"><?= esc($stats['duplicates']) ?></strong></div><div><span class="eyebrow">INVALID ATTEMPTS</span><strong class="danger-text" data-testid="dashboard-invalid"><?= esc($stats['invalid']) ?></strong></div></div>
    <div class="admin-grid-main"><div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">REGISTRATION PULSE</span><h2>Recent registrations</h2></div><a href="<?= base_url('admin/registrations') ?>" class="text-link">View all ↗</a></div><div class="table-list"><?php foreach(array_slice($recent,0,6) as $registration): ?><a class="list-row" href="<?= base_url('admin/registrations/'.$registration['registration_id']) ?>" data-testid="recent-registration-row"><div class="avatar-circle"><?= esc(strtoupper(substr($registration['participant_name'],0,1))) ?></div><div class="list-primary"><strong><?= esc($registration['participant_name']) ?></strong><span><?= esc($registration['event_name']) ?></span></div><span class="mono list-id"><?= esc($registration['registration_id']) ?></span><span class="<?= status_class($registration['status']) ?>"><?= esc(strtoupper(str_replace('_',' ',$registration['status']))) ?></span></a><?php endforeach ?></div></div>
      <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">TOP EVENTS</span><h2>Live performance</h2></div></div><div class="ranking-list"><?php foreach($topEvents as $index=>$event): ?><div class="ranking-row" data-testid="top-event-row"><span class="mono">0<?= $index+1 ?></span><div><strong><?= esc($event['name']) ?></strong><small><?= esc(money($event['revenue'])) ?> verified</small></div><b><?= esc($event['registrations']) ?></b></div><?php endforeach ?></div><a href="<?= base_url('admin/events/new') ?>" class="button button-yellow full-width" data-testid="admin-create-event-button">Create an event <span>↗</span></a></div></div>
    <div class="admin-panel dashboard-scans"><div class="panel-heading"><div><span class="eyebrow">LIVE ENTRY FEED</span><h2>Recent scan decisions</h2></div><a href="<?= base_url('admin/attendance') ?>" class="text-link">Open attendance ↗</a></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Time</th><th>Participant</th><th>Event</th><th>Gate</th><th>Decision</th></tr></thead><tbody><?php foreach($recentScans as $scan): ?><tr data-testid="dashboard-scan-row"><td class="mono"><?= esc(date('H:i:s',strtotime($scan['attempted_at']))) ?></td><td><?= esc($scan['participant_name']?:'Unknown token') ?><span class="table-sub"><?= esc($scan['registration_id']?:'—') ?></span></td><td><?= esc($scan['event_name']?:'—') ?></td><td><?= esc($scan['gate_name']?:'—') ?></td><td><span class="<?= status_class($scan['status']) ?>"><?= esc(strtoupper($scan['status'])) ?></span></td></tr><?php endforeach ?></tbody></table></div></div>
  </section>
</main>