<?php
$value=static fn(string $key,$default='')=>$event[$key]??old($key,$default);
$statusOptions=['draft','scheduled','registration_open','registration_closed','full','live','completed','cancelled','archived'];
$dayRows=$days?:[['label'=>'Day 1','event_date'=>'']];
$fieldRows=$fields?:[['label'=>'','field_name'=>'','field_type'=>'text','options_json'=>null,'is_required'=>0]];
?>
<main class="admin-shell">
  <?= view('partials/admin_sidebar',['active'=>'events']) ?>
  <section class="admin-content">
    <div class="admin-topbar"><div><span class="eyebrow accent">PROGRAMME BUILDER / COMPLETE CONFIGURATION</span><h1 data-testid="event-form-title"><?= $event?'Edit event':'New event' ?></h1></div><a class="button button-ghost" href="<?= base_url('admin/events') ?>">Back to events</a></div>
    <form method="post" action="<?= $event?base_url('admin/events/'.$event['id']):base_url('admin/events') ?>" class="event-builder" data-testid="admin-event-form">
      <input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><?php if($event): ?><input type="hidden" name="id" value="<?= esc($event['id']) ?>"><?php endif ?>
      <section class="admin-panel builder-section"><div class="panel-heading"><div><span class="eyebrow">01 / IDENTITY</span><h2>Event details</h2></div></div><div class="form-grid">
        <label>Category<select name="category_id" required data-testid="event-category-input"><option value="">Select category</option><?php foreach($categories as $category): ?><option value="<?= esc($category['id']) ?>" <?= (int)$value('category_id')===(int)$category['id']?'selected':'' ?>><?= esc($category['name']) ?></option><?php endforeach ?></select></label>
        <label>Event name<input name="name" value="<?= esc($value('name')) ?>" required data-testid="event-name-input"></label><label>Slug<input name="slug" value="<?= esc($value('slug')) ?>" placeholder="auto-generated" data-testid="event-slug-input"></label>
        <label>Event type<select name="event_type" data-testid="event-type-select"><?php foreach(['competition','workshop','sports','hackathon','quiz','other'] as $type): ?><option value="<?= $type ?>" <?= $value('event_type','competition')===$type?'selected':'' ?>><?= esc(ucfirst($type)) ?></option><?php endforeach ?></select></label>
        <label class="full-field">Short description<input name="short_description" value="<?= esc($value('short_description')) ?>" maxlength="300" data-testid="event-short-description-input"></label><label class="full-field">Full description<textarea name="description" rows="5" data-testid="event-description-input"><?= esc($value('description')) ?></textarea></label>
        <label>Banner URL<input type="url" name="banner_path" value="<?= esc($value('banner_path')) ?>" data-testid="event-banner-input"></label><label>Thumbnail URL<input type="url" name="thumbnail_path" value="<?= esc($value('thumbnail_path')) ?>" data-testid="event-thumbnail-input"></label>
      </div></section>
      <section class="admin-panel builder-section"><div class="panel-heading"><div><span class="eyebrow">02 / REGISTRATION & PAYMENT</span><h2>Entry configuration</h2></div></div><div class="form-grid">
        <label>Registration type<select name="registration_type" data-testid="event-registration-type-select"><?php foreach(['individual','team'] as $type): ?><option value="<?= $type ?>" <?= $value('registration_type','individual')===$type?'selected':'' ?>><?= esc(ucfirst($type)) ?></option><?php endforeach ?></select></label><label>Capacity (0 = unlimited)<input type="number" name="capacity" min="0" value="<?= esc($value('capacity',0)) ?>" data-testid="event-capacity-input"></label>
        <label>SAGEian fee (₹)<input type="number" name="sageian_fee" min="0" step="0.01" value="<?= esc($value('sageian_fee',$value('fee',0))) ?>" data-testid="event-sageian-fee-input"></label><label>Non-SAGEian fee (₹)<input type="number" name="non_sageian_fee" min="0" step="0.01" value="<?= esc($value('non_sageian_fee',$value('fee',0))) ?>" data-testid="event-non-sageian-fee-input"></label><label>Tax (₹)<input type="number" name="tax_amount" min="0" step="0.01" value="<?= esc($value('tax_amount',0)) ?>" data-testid="event-tax-input"></label><label>Discount (₹)<input type="number" name="discount_amount" min="0" step="0.01" value="<?= esc($value('discount_amount',0)) ?>" data-testid="event-discount-input"></label>
        <label>Minimum team size<input type="number" name="min_team_size" min="1" value="<?= esc($value('min_team_size')) ?>" data-testid="event-team-min-input"></label><label>Maximum team size<input type="number" name="max_team_size" min="1" value="<?= esc($value('max_team_size')) ?>" data-testid="event-team-max-input"></label>
        <label>Registration opens<input type="datetime-local" name="registration_start" value="<?= esc($value('registration_start')?date('Y-m-d\TH:i',strtotime($value('registration_start'))):'') ?>" data-testid="event-registration-start-input"></label><label>Registration closes<input type="datetime-local" name="registration_end" value="<?= esc($value('registration_end')?date('Y-m-d\TH:i',strtotime($value('registration_end'))):'') ?>" data-testid="event-registration-end-input"></label>
        <label class="checkbox-label"><input type="checkbox" name="payment_required" value="1" <?= $value('payment_required',max((float)$value('sageian_fee',$value('fee',0)),(float)$value('non_sageian_fee',$value('fee',0)))>0?1:0)?'checked':'' ?> data-testid="event-payment-required-checkbox"> Payment required</label><label class="checkbox-label"><input type="checkbox" name="is_featured" value="1" <?= $value('is_featured')?'checked':'' ?> data-testid="event-featured-checkbox"> Featured event</label>
      </div></section>
      <section class="admin-panel builder-section"><div class="panel-heading"><div><span class="eyebrow">03 / SCHEDULE & ACCESS</span><h2>Event operations</h2></div></div><div class="form-grid"><label>Event starts<input type="datetime-local" name="event_start" value="<?= esc($value('event_start')?date('Y-m-d\TH:i',strtotime($value('event_start'))):'') ?>" data-testid="event-start-input"></label><label>Event ends<input type="datetime-local" name="event_end" value="<?= esc($value('event_end')?date('Y-m-d\TH:i',strtotime($value('event_end'))):'') ?>" data-testid="event-end-input"></label><label>Venue<input name="venue" value="<?= esc($value('venue')) ?>" data-testid="event-venue-input"></label><label>Status<select name="status" data-testid="event-status-select"><?php foreach($statusOptions as $status): ?><option value="<?= $status ?>" <?= $value('status','draft')===$status?'selected':'' ?>><?= esc(ucwords(str_replace('_',' ',$status))) ?></option><?php endforeach ?></select></label><label class="full-field">Eligibility<input name="eligibility" value="<?= esc($value('eligibility')) ?>" data-testid="event-eligibility-input"></label><label class="full-field">Rules<textarea name="rules" rows="4" data-testid="event-rules-input"><?= esc($value('rules')) ?></textarea></label><label class="full-field">Prizes<textarea name="prizes" rows="3" data-testid="event-prizes-input"><?= esc($value('prizes')) ?></textarea></label><label class="full-field">Refund policy<textarea name="refund_policy" rows="3" data-testid="event-refund-input"><?= esc($value('refund_policy')) ?></textarea></label><label class="full-field">Coordinator / contact<input name="contact_details" value="<?= esc($value('contact_details')) ?>" data-testid="event-contact-input"></label></div>
        <div class="repeater-heading"><div><span class="eyebrow">EVENT DAYS</span><p>One QR can be used once on each configured day.</p></div><button type="button" class="table-action" id="add-event-day" data-testid="add-event-day-button">Add day</button></div><div id="event-days-list" class="repeater-list"><?php foreach($dayRows as $index=>$day): ?><div class="repeater-row" data-testid="event-day-row"><label>Label<input name="day_label[]" value="<?= esc($day['label']) ?>" placeholder="Day <?= $index+1 ?>"></label><label>Date<input type="date" name="day_date[]" value="<?= esc($day['event_date']) ?>"></label><button type="button" class="table-action danger-action remove-row">Remove</button></div><?php endforeach ?></div>
      </section>
      <section class="admin-panel builder-section"><div class="panel-heading"><div><span class="eyebrow">04 / DYNAMIC FORM</span><h2>Event-specific fields</h2></div><button type="button" class="table-action" id="add-registration-field" data-testid="add-registration-field-button">Add field</button></div><p class="builder-help">Core name, email, mobile and institution fields are always collected. Add event-specific questions below.</p><div id="registration-fields-list" class="repeater-list"><?php foreach($fieldRows as $index=>$field): $options=$field['options_json']?implode(', ',json_decode($field['options_json'],true)?:[]):''; ?><div class="field-builder-row" data-testid="registration-field-row"><label>Label<input name="field_label[]" value="<?= esc($field['label']) ?>"></label><label>Field name<input name="field_name[]" value="<?= esc($field['field_name']) ?>" placeholder="dance_style"></label><label>Type<select name="field_type[]"><?php foreach(['text','number','email','phone','date','select','radio','checkbox','textarea','file'] as $type): ?><option value="<?= $type ?>" <?= $field['field_type']===$type?'selected':'' ?>><?= esc(ucfirst($type)) ?></option><?php endforeach ?></select></label><label>Options (comma separated)<input name="field_options[]" value="<?= esc($options) ?>"></label><label class="checkbox-label"><input type="checkbox" name="field_required[]" value="<?= $index ?>" <?= $field['is_required']?'checked':'' ?>> Required</label><button type="button" class="table-action danger-action remove-row">Remove</button></div><?php endforeach ?></div></section>
      <div class="builder-save"><span class="notice-warning">Publishing immediately updates the public database-driven event catalogue.</span><button class="button button-yellow" type="submit" data-testid="event-save-button"><?= $event?'Save event':'Create event' ?> <span>↗</span></button></div>
    </form>
  </section>
</main>