<main class="admin-shell">
  <?= view('partials/admin_sidebar',['active'=>'registrations']) ?>
  <section class="admin-content">
    <div class="admin-topbar"><div><span class="eyebrow accent">PARTICIPANT RECORD</span><h1 data-testid="registration-detail-title"><?= esc($registration['participant_name']) ?></h1></div><a class="button button-ghost" href="<?= base_url('admin/registrations') ?>">Back to list</a></div>
    <div class="admin-detail-grid">
      <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">REGISTRATION</span><h2 data-testid="detail-registration-id"><?= esc($registration['registration_id']) ?></h2></div><span class="<?= status_class($registration['status']) ?>" data-testid="detail-registration-status"><?= esc(strtoupper(str_replace('_',' ',$registration['status']))) ?></span></div><dl class="detail-list"><div><dt>Event</dt><dd><?= esc($registration['event_name']) ?> · <?= esc($registration['category_name']) ?></dd></div><div><dt>Email</dt><dd><?= esc($registration['email']) ?></dd></div><div><dt>Mobile</dt><dd><?= esc($registration['mobile']) ?></dd></div><div><dt>Institution</dt><dd><?= esc($registration['college']) ?></dd></div><div><dt>Payment</dt><dd><?= esc(strtoupper($registration['payment_status']??'NONE')) ?> · <?= esc(money($registration['total_amount'])) ?></dd></div><div><dt>Pass</dt><dd><?= esc(strtoupper($registration['token_status']??'NONE')) ?> · hint <?= esc($registration['token_hint']??'—') ?></dd></div></dl>
        <?php if($values): ?><div class="panel-subsection"><span class="eyebrow">EVENT RESPONSES</span><?php foreach($values as $value): ?><p><strong><?= esc($value['label']) ?>:</strong> <?= esc($value['value_text']) ?></p><?php endforeach ?></div><?php endif ?>
        <?php if($members): ?><div class="panel-subsection"><span class="eyebrow">TEAM MEMBERS</span><?php foreach($members as $member): ?><p><?= esc($member['name']) ?></p><?php endforeach ?></div><?php endif ?>
      </div>
      <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">CONTROL</span><h2>Pass actions</h2></div></div><div class="action-stack"><form method="post" action="<?= base_url('admin/registrations/'.$registration['registration_id'].'/status') ?>"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><button class="button button-ghost full-width" name="action" value="resend" data-testid="registration-resend-button">Queue pass email</button></form><form method="post" action="<?= base_url('admin/registrations/'.$registration['registration_id'].'/status') ?>"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><button class="button button-ghost full-width" name="action" value="revoke" data-confirm="Revoke this QR immediately?" data-testid="registration-revoke-button">Revoke QR</button></form><form method="post" action="<?= base_url('admin/registrations/'.$registration['registration_id'].'/status') ?>"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><button class="button button-ghost full-width" name="action" value="restore" data-testid="registration-restore-button">Restore paid pass</button></form><form method="post" action="<?= base_url('admin/registrations/'.$registration['registration_id'].'/status') ?>"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><button class="button button-ghost full-width danger-action" name="action" value="cancel" data-confirm="Cancel this registration and revoke its QR?" data-testid="registration-cancel-button">Cancel registration</button></form></div></div>
    </div>
    <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">DAY-WISE HISTORY</span><h2>Attendance</h2></div></div><div class="timeline-list"><?php foreach($attendance as $entry): ?><div class="timeline-row" data-testid="participant-attendance-row"><div><strong><?= esc($entry['label']) ?></strong><span><?= esc($entry['event_date']) ?></span></div><?php if($entry['entry_time']): ?><span class="status status-success">ENTERED · <?= esc(date('h:i A',strtotime($entry['entry_time']))) ?></span><span><?= esc(($entry['gate_name']?:'Gate').' · '.($entry['scanner_name']?:'Scanner')) ?></span><?php else: ?><span class="status">NOT ENTERED</span><span>—</span><?php endif ?></div><?php endforeach ?></div></div>
  </section>
</main>