<main class="admin-shell">
  <?= view('partials/admin_sidebar',['active'=>'scanners']) ?>
  <section class="admin-content">
    <div class="admin-topbar"><div><span class="eyebrow accent">AUTHORIZED ENTRY CONTROL</span><h1 data-testid="scanner-access-title">Scanner access</h1></div><a class="button button-yellow" href="<?= base_url('scanner') ?>" data-testid="launch-scanner-link">Launch scanner ↗</a></div>
    <div class="admin-split">
      <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">ASSIGNMENT</span><h2>Assign a scanner</h2></div></div><form method="post" action="<?= base_url('admin/scanner-assignments') ?>" class="admin-form" data-testid="scanner-assignment-form"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><label>Scanner user<select name="user_id" required data-testid="assignment-scanner-select"><option value="">Select scanner</option><?php foreach($scanners as $scanner): ?><option value="<?= esc($scanner['id']) ?>"><?= esc($scanner['name'].' · '.$scanner['email']) ?></option><?php endforeach ?></select></label><label>Event<select id="assignment-event" name="event_id" required data-testid="assignment-event-select"><option value="">Select event</option><?php foreach($events as $event): ?><option value="<?= esc($event['id']) ?>"><?= esc($event['name']) ?></option><?php endforeach ?></select></label><label>Event day<select id="assignment-day" name="event_day_id" required data-testid="assignment-day-select"><option value="">Select day</option><?php foreach($days as $day): ?><option value="<?= esc($day['id']) ?>" data-event="<?= esc($day['event_id']) ?>"><?= esc($day['label'].' · '.$day['event_date']) ?></option><?php endforeach ?></select></label><label>Gate<select name="gate_id" required data-testid="assignment-gate-select"><option value="">Select gate</option><?php foreach($gates as $gate): if(!$gate['is_active'])continue; ?><option value="<?= esc($gate['id']) ?>"><?= esc($gate['name']) ?></option><?php endforeach ?></select></label><button class="button button-yellow" type="submit" data-testid="assignment-save-button">Create assignment <span>↗</span></button></form>
        <div class="repeater-heading"><div><span class="eyebrow">NEW GATE</span><p>Create an entry point before assigning staff.</p></div></div><form method="post" action="<?= base_url('admin/gates') ?>" class="admin-form" data-testid="gate-create-form"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><label>Programme<select name="programme_id" required data-testid="gate-programme-select"><?php foreach($programmes as $programme): ?><option value="<?= esc($programme['id']) ?>"><?= esc($programme['name']) ?></option><?php endforeach ?></select></label><label>Gate name<input name="name" required placeholder="Gate 2 · East Entry" data-testid="gate-name-input"></label><button class="button button-ghost" type="submit" data-testid="gate-create-button">Add gate</button></form></div>
      <div class="admin-panel"><div class="panel-heading"><div><span class="eyebrow">CURRENT ACCESS</span><h2 data-testid="assignment-count"><?= count($assignments) ?> assignments</h2></div></div><div class="stack-list"><?php foreach($assignments as $assignment): ?><div class="editable-row" data-testid="scanner-assignment-row"><div class="editable-row-head"><div><strong><?= esc($assignment['scanner_name']) ?></strong><span class="table-sub"><?= esc($assignment['email']) ?></span></div><span class="<?= $assignment['is_active']?'status status-success':'status status-warning' ?>"><?= $assignment['is_active']?'ACTIVE':'REVOKED' ?></span></div><p><?= esc($assignment['event_name']) ?> · <?= esc($assignment['day_label'].' '.$assignment['event_date']) ?> · <?= esc($assignment['gate_name']) ?></p><?php if($assignment['is_active']): ?><form method="post" action="<?= base_url('admin/scanner-assignments/'.$assignment['id'].'/delete') ?>"><input type="hidden" name="<?= csrf_token() ?>" value="<?= csrf_hash() ?>"><button class="table-action danger-action" type="submit" data-confirm="Revoke this scanner assignment?" data-testid="assignment-revoke-button">Revoke access</button></form><?php endif ?></div><?php endforeach ?></div></div>
    </div>
  </section>
</main>