<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class ExtendOperationalTables extends Migration
{
    public function up(): void
    {
        $this->db->query("ALTER TABLE qr_tokens ADD COLUMN token_ciphertext TEXT NULL AFTER token_hint");
        $tables = [
            "CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, description VARCHAR(255) NULL)",
            "CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), CONSTRAINT fk_rp_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, CONSTRAINT fk_rp_permission FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS scanner_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, event_id BIGINT UNSIGNED NOT NULL, event_day_id BIGINT UNSIGNED NOT NULL, gate_id BIGINT UNSIGNED NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, UNIQUE KEY scanner_scope(user_id,event_id,event_day_id,gate_id), CONSTRAINT fk_sa_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_sa_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE, CONSTRAINT fk_sa_day FOREIGN KEY(event_day_id) REFERENCES event_days(id) ON DELETE CASCADE, CONSTRAINT fk_sa_gate FOREIGN KEY(gate_id) REFERENCES gates(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS event_schedules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, event_day_id BIGINT UNSIGNED NULL, title VARCHAR(180) NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NULL, venue VARCHAR(180) NULL, display_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY schedule_event(event_id,starts_at), CONSTRAINT fk_schedule_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE, CONSTRAINT fk_schedule_day FOREIGN KEY(event_day_id) REFERENCES event_days(id) ON DELETE SET NULL)",
            "CREATE TABLE IF NOT EXISTS event_speakers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, designation VARCHAR(160) NULL, organization VARCHAR(180) NULL, bio TEXT NULL, role VARCHAR(60) NULL, photo_path VARCHAR(255) NULL, display_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_speaker_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS event_galleries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, album VARCHAR(140) NULL, image_path VARCHAR(255) NOT NULL, caption VARCHAR(255) NULL, event_date DATE NULL, display_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, KEY gallery_event(event_id,display_order), CONSTRAINT fk_gallery_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS registration_forms (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL UNIQUE, title VARCHAR(180) NOT NULL, instructions TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_form_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS payment_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, payment_id BIGINT UNSIGNED NOT NULL, action VARCHAR(60) NOT NULL, gateway_reference VARCHAR(160) NULL, status VARCHAR(60) NOT NULL, response_digest CHAR(64) NULL, created_at DATETIME NOT NULL, KEY pt_payment(payment_id,created_at), CONSTRAINT fk_pt_payment FOREIGN KEY(payment_id) REFERENCES payments(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS coupons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(60) NOT NULL UNIQUE, discount_type ENUM('percent','fixed') NOT NULL, discount_value DECIMAL(10,2) NOT NULL, maximum_usage INT NULL, minimum_amount DECIMAL(10,2) NOT NULL DEFAULT 0, starts_at DATETIME NULL, ends_at DATETIME NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)",
            "CREATE TABLE IF NOT EXISTS coupon_usages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, coupon_id BIGINT UNSIGNED NOT NULL, registration_id BIGINT UNSIGNED NOT NULL, discount_amount DECIMAL(10,2) NOT NULL, created_at DATETIME NOT NULL, UNIQUE KEY coupon_registration(coupon_id,registration_id), CONSTRAINT fk_cu_coupon FOREIGN KEY(coupon_id) REFERENCES coupons(id) ON DELETE RESTRICT, CONSTRAINT fk_cu_registration FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS email_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, template_key VARCHAR(100) NOT NULL UNIQUE, subject VARCHAR(255) NOT NULL, body_html MEDIUMTEXT NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)",
            "CREATE TABLE IF NOT EXISTS email_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL, template_key VARCHAR(100) NOT NULL, status ENUM('pending','processing','sent','failed') NOT NULL DEFAULT 'pending', attempts SMALLINT NOT NULL DEFAULT 0, available_at DATETIME NOT NULL, locked_at DATETIME NULL, last_error TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY email_queue(status,available_at), CONSTRAINT fk_email_job_registration FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS email_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NULL, recipient VARCHAR(190) NOT NULL, template_key VARCHAR(100) NOT NULL, subject VARCHAR(255) NOT NULL, status ENUM('sent','failed') NOT NULL, provider_reference VARCHAR(190) NULL, error_message TEXT NULL, created_at DATETIME NOT NULL, KEY email_log_registration(registration_id), CONSTRAINT fk_email_log_registration FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE SET NULL)",
            "CREATE TABLE IF NOT EXISTS notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, channel VARCHAR(40) NOT NULL, title VARCHAR(180) NOT NULL, body TEXT NOT NULL, read_at DATETIME NULL, created_at DATETIME NOT NULL, KEY notification_user(user_id,read_at), CONSTRAINT fk_notification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS uploaded_files (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, module VARCHAR(60) NOT NULL, record_id VARCHAR(80) NULL, original_name VARCHAR(255) NOT NULL, storage_path VARCHAR(255) NOT NULL UNIQUE, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, CONSTRAINT fk_upload_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL)",
        ];
        foreach ($tables as $sql) $this->db->query($sql . ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    }

    public function down(): void
    {
        foreach (['uploaded_files','notifications','email_logs','email_jobs','email_templates','coupon_usages','coupons','payment_transactions','registration_forms','event_galleries','event_speakers','event_schedules','scanner_assignments','role_permissions','permissions'] as $table) $this->db->query("DROP TABLE IF EXISTS {$table}");
        $this->db->query('ALTER TABLE qr_tokens DROP COLUMN token_ciphertext');
    }
}