<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreatePlatformTables extends Migration
{
    public function up(): void
    {
        $tables = [
            'programmes' => "CREATE TABLE IF NOT EXISTS programmes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE, year SMALLINT NOT NULL, description TEXT NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', starts_on DATE NULL, ends_on DATE NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'categories' => "CREATE TABLE IF NOT EXISTS categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, programme_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT NULL, image_path VARCHAR(255) NULL, display_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY category_slug (programme_id,slug), KEY category_programme (programme_id), CONSTRAINT fk_category_programme FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'events' => "CREATE TABLE IF NOT EXISTS events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL UNIQUE, short_description VARCHAR(300) NULL, description TEXT NULL, banner_path VARCHAR(255) NULL, thumbnail_path VARCHAR(255) NULL, event_type ENUM('competition','workshop','sports','hackathon','quiz','other') NOT NULL DEFAULT 'competition', registration_type ENUM('individual','team','both') NOT NULL DEFAULT 'individual', fee DECIMAL(10,2) NOT NULL DEFAULT 0, capacity INT NOT NULL DEFAULT 0, min_team_size INT NULL, max_team_size INT NULL, registration_start DATETIME NULL, registration_end DATETIME NULL, event_start DATETIME NULL, event_end DATETIME NULL, venue VARCHAR(180) NULL, eligibility VARCHAR(255) NULL, rules TEXT NULL, prizes TEXT NULL, contact_details VARCHAR(255) NULL, status ENUM('draft','scheduled','registration_open','registration_closed','full','live','completed','cancelled','archived') NOT NULL DEFAULT 'draft', is_featured TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY event_slug (slug), KEY event_category_status (category_id,status), CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'event_days' => "CREATE TABLE IF NOT EXISTS event_days (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, label VARCHAR(80) NOT NULL, event_date DATE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY event_day (event_id,event_date), CONSTRAINT fk_day_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'registration_fields' => "CREATE TABLE IF NOT EXISTS registration_fields (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, label VARCHAR(160) NOT NULL, field_name VARCHAR(100) NOT NULL, field_type ENUM('text','number','email','phone','date','select','radio','checkbox','textarea','file') NOT NULL DEFAULT 'text', placeholder VARCHAR(180) NULL, options_json JSON NULL, is_required TINYINT(1) NOT NULL DEFAULT 0, display_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY event_field_name (event_id,field_name), CONSTRAINT fk_field_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'users' => "CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, phone VARCHAR(30) NULL, password_hash VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)",
            'roles' => "CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE)",
            'user_roles' => "CREATE TABLE IF NOT EXISTS user_roles (user_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY (user_id,role_id), CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE)",
            'registrations' => "CREATE TABLE IF NOT EXISTS registrations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, registration_id VARCHAR(60) NOT NULL UNIQUE, participant_name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL, mobile VARCHAR(30) NOT NULL, college VARCHAR(180) NULL, registration_type ENUM('individual','team') NOT NULL DEFAULT 'individual', team_name VARCHAR(160) NULL, total_amount DECIMAL(10,2) NOT NULL DEFAULT 0, status ENUM('pending_payment','confirmed','cancelled','rejected','completed') NOT NULL DEFAULT 'pending_payment', qr_status ENUM('active','suspended','cancelled','expired') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY registration_event (event_id), KEY registration_email (email), CONSTRAINT fk_registration_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            'registration_field_values' => "CREATE TABLE IF NOT EXISTS registration_field_values (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL, field_id BIGINT UNSIGNED NOT NULL, value_text TEXT NULL, created_at DATETIME NOT NULL, UNIQUE KEY registration_field (registration_id,field_id), CONSTRAINT fk_rfv_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE, CONSTRAINT fk_rfv_field FOREIGN KEY (field_id) REFERENCES registration_fields(id) ON DELETE CASCADE)",
            'registration_members' => "CREATE TABLE IF NOT EXISTS registration_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, email VARCHAR(190) NULL, mobile VARCHAR(30) NULL, college VARCHAR(180) NULL, created_at DATETIME NOT NULL, CONSTRAINT fk_member_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE)",
            'payments' => "CREATE TABLE IF NOT EXISTS payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL, txnid VARCHAR(80) NOT NULL UNIQUE, amount DECIMAL(10,2) NOT NULL, gateway VARCHAR(40) NOT NULL DEFAULT 'easebuzz', gateway_order_id VARCHAR(120) NULL, gateway_payment_id VARCHAR(120) NULL, status ENUM('created','pending','initiated','success','failed','cancelled','refunded','unknown') NOT NULL DEFAULT 'created', raw_reference TEXT NULL, paid_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY payment_status (status), CONSTRAINT fk_payment_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE RESTRICT)",
            'qr_tokens' => "CREATE TABLE IF NOT EXISTS qr_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL UNIQUE, token_hash CHAR(64) NOT NULL UNIQUE, token_hint VARCHAR(20) NOT NULL, status ENUM('active','revoked','expired') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, revoked_at DATETIME NULL, CONSTRAINT fk_qr_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE)",
            'gates' => "CREATE TABLE IF NOT EXISTS gates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, programme_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT fk_gate_programme FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE CASCADE)",
            'attendance' => "CREATE TABLE IF NOT EXISTS attendance (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT UNSIGNED NOT NULL, event_id BIGINT UNSIGNED NOT NULL, event_day_id BIGINT UNSIGNED NOT NULL, gate_id BIGINT UNSIGNED NULL, scanner_user_id BIGINT UNSIGNED NULL, entry_time DATETIME NOT NULL, status ENUM('allowed','duplicate','denied') NOT NULL DEFAULT 'allowed', reason VARCHAR(180) NULL, UNIQUE KEY daily_entry (event_id,registration_id,event_day_id), KEY attendance_registration (registration_id), KEY attendance_day (event_day_id), KEY attendance_event_time (event_id,entry_time), CONSTRAINT fk_att_registration FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE, CONSTRAINT fk_att_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE, CONSTRAINT fk_att_day FOREIGN KEY (event_day_id) REFERENCES event_days(id) ON DELETE CASCADE, CONSTRAINT fk_att_gate FOREIGN KEY (gate_id) REFERENCES gates(id) ON DELETE SET NULL, CONSTRAINT fk_att_scanner FOREIGN KEY (scanner_user_id) REFERENCES users(id) ON DELETE SET NULL)",
            'settings' => "CREATE TABLE IF NOT EXISTS settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(120) NOT NULL UNIQUE, setting_value TEXT NULL, is_secret TINYINT(1) NOT NULL DEFAULT 0, updated_by BIGINT UNSIGNED NULL, updated_at DATETIME NOT NULL)",
            'audit_logs' => "CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(160) NOT NULL, module VARCHAR(80) NOT NULL, record_id VARCHAR(80) NULL, ip_address VARCHAR(45) NULL, metadata_json JSON NULL, created_at DATETIME NOT NULL, KEY audit_action (action), KEY audit_created (created_at), CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL)",
        ];
        foreach ($tables as $sql) {
            $this->db->query($sql);
        }
    }

    public function down(): void
    {
        foreach (['audit_logs','settings','attendance','gates','qr_tokens','payments','registration_members','registration_field_values','registrations','user_roles','roles','users','registration_fields','event_days','events','categories','programmes'] as $table) {
            $this->db->query("DROP TABLE IF EXISTS {$table}");
        }
    }
}